### ISSUE TITLE
Isa kuch nai hoga bro 

### ISSUE THREAD

**Issue by raj22001** [dineshtamang14/Book_For_You#1]
kuch kar la toda kame

**Comment by dineshtamang14** [comment]
Working on it bro 😊

**Comment by dineshtamang14** [comment]
Tu kaam Mai hai kya ???

**Comment by raj22001** [comment]
Ha yaar Abe leave kar na wala Hu 😔  . muja WhatsApp call kar free hoga tabhi

**Comment by rupensoni** [comment]
> Ha yaar Abe leave kar na wala Hu 😔 . muja WhatsApp call kar free hoga tabhi

Hello Raj bhai I am Dinesh friend if you have any internship pls let me know in AWS cloud computing
